// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CTRL
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/SC)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        others - reserved
// 0x10 : Data signal of LoadValCnt_V
//        bit 15~0 - LoadValCnt_V[15:0] (Read/Write)
//        others   - reserved
// 0x14 : reserved
// 0x18 : Data signal of EN_V
//        bit 0  - EN_V[0] (Read/Write)
//        others - reserved
// 0x1c : reserved
// 0x20 : Data signal of Rst_V
//        bit 0  - Rst_V[0] (Read/Write)
//        others - reserved
// 0x24 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XPWM_CTRL_CTRL_ADDR_AP_CTRL           0x00
#define XPWM_CTRL_CTRL_ADDR_GIE               0x04
#define XPWM_CTRL_CTRL_ADDR_IER               0x08
#define XPWM_CTRL_CTRL_ADDR_ISR               0x0c
#define XPWM_CTRL_CTRL_ADDR_LOADVALCNT_V_DATA 0x10
#define XPWM_CTRL_CTRL_BITS_LOADVALCNT_V_DATA 16
#define XPWM_CTRL_CTRL_ADDR_EN_V_DATA         0x18
#define XPWM_CTRL_CTRL_BITS_EN_V_DATA         1
#define XPWM_CTRL_CTRL_ADDR_RST_V_DATA        0x20
#define XPWM_CTRL_CTRL_BITS_RST_V_DATA        1

