// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xpwm_ctrl.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XPwm_ctrl_CfgInitialize(XPwm_ctrl *InstancePtr, XPwm_ctrl_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_BaseAddress = ConfigPtr->Ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XPwm_ctrl_Start(XPwm_ctrl *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_ctrl_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_AP_CTRL) & 0x80;
    XPwm_ctrl_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XPwm_ctrl_IsDone(XPwm_ctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_ctrl_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XPwm_ctrl_IsIdle(XPwm_ctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_ctrl_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XPwm_ctrl_IsReady(XPwm_ctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_ctrl_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XPwm_ctrl_EnableAutoRestart(XPwm_ctrl *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_ctrl_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_AP_CTRL, 0x80);
}

void XPwm_ctrl_DisableAutoRestart(XPwm_ctrl *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_ctrl_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_AP_CTRL, 0);
}

void XPwm_ctrl_Set_LoadValCnt_V(XPwm_ctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_ctrl_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_LOADVALCNT_V_DATA, Data);
}

u32 XPwm_ctrl_Get_LoadValCnt_V(XPwm_ctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_ctrl_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_LOADVALCNT_V_DATA);
    return Data;
}

void XPwm_ctrl_Set_EN_V(XPwm_ctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_ctrl_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_EN_V_DATA, Data);
}

u32 XPwm_ctrl_Get_EN_V(XPwm_ctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_ctrl_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_EN_V_DATA);
    return Data;
}

void XPwm_ctrl_Set_Rst_V(XPwm_ctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_ctrl_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_RST_V_DATA, Data);
}

u32 XPwm_ctrl_Get_Rst_V(XPwm_ctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_ctrl_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_RST_V_DATA);
    return Data;
}

void XPwm_ctrl_InterruptGlobalEnable(XPwm_ctrl *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_ctrl_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_GIE, 1);
}

void XPwm_ctrl_InterruptGlobalDisable(XPwm_ctrl *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_ctrl_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_GIE, 0);
}

void XPwm_ctrl_InterruptEnable(XPwm_ctrl *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPwm_ctrl_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_IER);
    XPwm_ctrl_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_IER, Register | Mask);
}

void XPwm_ctrl_InterruptDisable(XPwm_ctrl *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPwm_ctrl_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_IER);
    XPwm_ctrl_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_IER, Register & (~Mask));
}

void XPwm_ctrl_InterruptClear(XPwm_ctrl *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_ctrl_WriteReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_ISR, Mask);
}

u32 XPwm_ctrl_InterruptGetEnabled(XPwm_ctrl *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPwm_ctrl_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_IER);
}

u32 XPwm_ctrl_InterruptGetStatus(XPwm_ctrl *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPwm_ctrl_ReadReg(InstancePtr->Ctrl_BaseAddress, XPWM_CTRL_CTRL_ADDR_ISR);
}

