# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/minized_pwm.xdc

# Block Designs: bd/Subsys/Subsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Subsys || ORIG_REF_NAME==Subsys} -quiet] -quiet

# IP: bd/Subsys/ip/Subsys_processing_system7_0_0/Subsys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Subsys_processing_system7_0_0 || ORIG_REF_NAME==Subsys_processing_system7_0_0} -quiet] -quiet

# IP: bd/Subsys/ip/Subsys_PWM_0_0/Subsys_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Subsys_PWM_0_0 || ORIG_REF_NAME==Subsys_PWM_0_0} -quiet] -quiet

# IP: bd/Subsys/ip/Subsys_PWM_CTRL_0_0/Subsys_PWM_CTRL_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Subsys_PWM_CTRL_0_0 || ORIG_REF_NAME==Subsys_PWM_CTRL_0_0} -quiet] -quiet

# IP: bd/Subsys/ip/Subsys_proc_sys_reset_0_0/Subsys_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Subsys_proc_sys_reset_0_0 || ORIG_REF_NAME==Subsys_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Subsys/ip/Subsys_axi_interconnect_0_0/Subsys_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Subsys_axi_interconnect_0_0 || ORIG_REF_NAME==Subsys_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Subsys/ip/Subsys_auto_pc_0/Subsys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Subsys_auto_pc_0 || ORIG_REF_NAME==Subsys_auto_pc_0} -quiet] -quiet

# XDC: bd/Subsys/ip/Subsys_processing_system7_0_0/Subsys_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Subsys_processing_system7_0_0 || ORIG_REF_NAME==Subsys_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Subsys/ip/Subsys_PWM_0_0/constraints/PWM_ooc.xdc

# XDC: bd/Subsys/ip/Subsys_PWM_CTRL_0_0/constraints/PWM_CTRL_ooc.xdc

# XDC: bd/Subsys/ip/Subsys_proc_sys_reset_0_0/Subsys_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Subsys_proc_sys_reset_0_0 || ORIG_REF_NAME==Subsys_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Subsys/ip/Subsys_proc_sys_reset_0_0/Subsys_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Subsys_proc_sys_reset_0_0 || ORIG_REF_NAME==Subsys_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Subsys/ip/Subsys_proc_sys_reset_0_0/Subsys_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/Subsys/ip/Subsys_auto_pc_0/Subsys_auto_pc_0_ooc.xdc

# XDC: bd/Subsys/Subsys_ooc.xdc
