# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z007sclg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/XilinxPrj/PWM_Minized/PWM_Minized.cache/wt [current_project]
set_property parent.project_path D:/XilinxPrj/PWM_Minized/PWM_Minized.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:minized:part0:1.2 [current_project]
set_property ip_repo_paths {
  d:/XilinxHLS_Prj/test/IP_PWM/PWM/impl/ip
  d:/XilinxHLS_Prj/test/IP_PWM/PWM_CTRL/impl/ip
} [current_project]
set_property ip_output_repo d:/XilinxPrj/PWM_Minized/PWM_Minized.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/XilinxPrj/PWM_Minized/PWM_Minized.srcs/sources_1/bd/Subsys/hdl/Subsys_wrapper.v
add_files D:/XilinxPrj/PWM_Minized/PWM_Minized.srcs/sources_1/bd/Subsys/Subsys.bd
set_property used_in_implementation false [get_files -all d:/XilinxPrj/PWM_Minized/PWM_Minized.srcs/sources_1/bd/Subsys/ip/Subsys_processing_system7_0_0/Subsys_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/XilinxPrj/PWM_Minized/PWM_Minized.srcs/sources_1/bd/Subsys/ip/Subsys_PWM_0_0/constraints/PWM_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/XilinxPrj/PWM_Minized/PWM_Minized.srcs/sources_1/bd/Subsys/ip/Subsys_PWM_CTRL_0_0/constraints/PWM_CTRL_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/XilinxPrj/PWM_Minized/PWM_Minized.srcs/sources_1/bd/Subsys/ip/Subsys_proc_sys_reset_0_0/Subsys_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/XilinxPrj/PWM_Minized/PWM_Minized.srcs/sources_1/bd/Subsys/ip/Subsys_proc_sys_reset_0_0/Subsys_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/XilinxPrj/PWM_Minized/PWM_Minized.srcs/sources_1/bd/Subsys/ip/Subsys_proc_sys_reset_0_0/Subsys_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/XilinxPrj/PWM_Minized/PWM_Minized.srcs/sources_1/bd/Subsys/ip/Subsys_auto_pc_0/Subsys_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/XilinxPrj/PWM_Minized/PWM_Minized.srcs/sources_1/bd/Subsys/Subsys_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/XilinxPrj/PWM_Minized/PWM_Minized.srcs/constrs_1/new/minized_pwm.xdc
set_property used_in_implementation false [get_files D:/XilinxPrj/PWM_Minized/PWM_Minized.srcs/constrs_1/new/minized_pwm.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Subsys_wrapper -part xc7z007sclg225-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Subsys_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Subsys_wrapper_utilization_synth.rpt -pb Subsys_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
